services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: z106-zookeeper-1
    ports:
      - "2181:2181"
    networks:
      - kafka_network

  kafka:
    image: wurstmeister/kafka:latest
    container_name: z106-kafka-1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENER_NAME: INSIDE
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
    networks:
      - kafka_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  spark:
    image: bitnami/spark:latest
    container_name: z106-spark-1
    environment:
      - SPARK_MODE=master
    ports:
      - "4040:4040"
      - "7077:7077"  # Porta do Spark Master
    networks:
      - kafka_network
    volumes:
      - ./spark-app:/app  # Volume para os arquivos Python
      - ./output:/output  # Volume para armazenar os arquivos Parquet e CSV

  spark-worker:
    image: bitnami/spark:latest
    container_name: z106-spark-worker-1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
    depends_on:
      - spark
    networks:
      - kafka_network
    volumes:
      - ./spark-app:/app
      - ./output:/output

networks:
  kafka_network:
    driver: bridge
